// StockPro Inventory Management System
// Service: Alert Service | Model: Alert
// Developer: Suru | April 2026
// Description: Represents an alert/notification in the system

namespace AlertService.Models
{
    public class Alert
    {
        // Unique ID auto-generated by database
        public int Id { get; set; }

        // Who receives this alert (user ID)
        public int RecipientId { get; set; }

        // Alert type: LOW_STOCK, OVERSTOCK, PO_PENDING, OVERDUE_RECEIPT, SYSTEM
        public string Type { get; set; } = "";

        // Severity: INFO, WARNING, CRITICAL
        public string Severity { get; set; } = "INFO";

        // Short title of the alert
        public string Title { get; set; } = "";

        // Full alert message
        public string Message { get; set; } = "";

        // Related product ID (if applicable)
        public int? RelatedProductId { get; set; }

        // Related warehouse ID (if applicable)
        public int? RelatedWarehouseId { get; set; }

        // Channel: IN_APP or EMAIL
        public string Channel { get; set; } = "IN_APP";

        // Has the recipient read this alert?
        public bool IsRead { get; set; } = false;

        // Has the recipient acknowledged this alert?
        public bool IsAcknowledged { get; set; } = false;

        // When alert was created
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}