// StockPro Inventory Management System
// Service: Auth Service
// Model: User
// Developer: Suru | April 2026
// Description: Represents a system user with role-based access

namespace AuthService.Models
{
    public class User
    {
        // Unique ID for every user (auto-generated by database)
        public int Id { get; set; }

        // Username used for login
        public string Username { get; set; } = "";

        // Hashed password (never store plain text)
        public string PasswordHash { get; set; } = "";

        // Role: Admin, Manager, Staff, Viewer
        public string Role { get; set; } = "Staff";

        // Is this account active?
        public bool IsActive { get; set; } = true;

        // When was this account created
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}