// StockPro Inventory Management System
// Service: Product Service | Model: Product
// Developer: Suru | April 2026
// Description: Represents a product/item in the inventory catalogue

namespace ProductService.Models
{
    public class Product
    {
        // Unique ID auto-generated by database
        public int Id { get; set; }

        // Stock Keeping Unit - unique product code
        public string SKU { get; set; } = "";

        // Product name
        public string Name { get; set; } = "";

        // Product description
        public string Description { get; set; } = "";

        // Category e.g. Electronics, Clothing
        public string Category { get; set; } = "";

        // Brand name
        public string Brand { get; set; } = "";

        // Unit of measure e.g. pieces, kg, litres
        public string UnitOfMeasure { get; set; } = "";

        // Cost price - what we pay supplier
        public decimal CostPrice { get; set; }

        // Selling price - what we charge customer
        public decimal SellingPrice { get; set; }

        // Barcode for QR scanning feature
        public string Barcode { get; set; } = "";

        // Minimum stock level - triggers low stock alert
        public int ReorderLevel { get; set; }

        // Maximum stock level - triggers overstock alert
        public int MaxStockLevel { get; set; }

        // Lead time in days to receive from supplier
        public int LeadTimeDays { get; set; }

        // Is product active or deactivated
        public bool IsActive { get; set; } = true;

        // When product was added to system
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        // When product was last updated
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    }
}