// StockPro Inventory Management System
// Service: Purchase Service | Model: PurchaseOrder
// Developer: Suru | April 2026
// Description: Represents a purchase order sent to a supplier

namespace PurchaseService.Models
{
    public class PurchaseOrder
    {
        // Unique PO ID auto-generated by database
        public int Id { get; set; }

        // Supplier this PO is sent to
        public int SupplierId { get; set; }

        // Warehouse where goods will be received
        public int WarehouseId { get; set; }

        // User who created this PO
        public int CreatedById { get; set; }

        // Status: Draft, Pending, Approved, PartiallyReceived, FullyReceived, Cancelled
        public string Status { get; set; } = "Draft";

        // Total amount of this PO
        public decimal TotalAmount { get; set; }

        // Date PO was created
        public DateTime OrderDate { get; set; } = DateTime.UtcNow;

        // Expected delivery date
        public DateTime ExpectedDate { get; set; }

        // Actual received date
        public DateTime? ReceivedDate { get; set; }

        // Reference number e.g. PO-2026-001
        public string ReferenceNumber { get; set; } = "";

        // Additional notes
        public string Notes { get; set; } = "";

        // Line items in this PO
        public List<POLineItem> LineItems { get; set; } = new();

        // When record was created
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}