// StockPro Inventory Management System
// Service: Warehouse Service | Model: Warehouse
// Developer: Suru | April 2026
// Description: Represents a physical warehouse location

namespace WarehouseService.Models
{
    public class Warehouse
    {
        // Unique ID auto-generated by database
        public int Id { get; set; }

        // Warehouse name e.g. "Delhi Warehouse"
        public string Name { get; set; } = "";

        // Physical address of warehouse
        public string Address { get; set; } = "";

        // City where warehouse is located
        public string City { get; set; } = "";

        // Maximum capacity in units
        public int Capacity { get; set; }

        // Manager user ID assigned to this warehouse
        public int? ManagerId { get; set; }

        // Is warehouse currently active
        public bool IsActive { get; set; } = true;

        // When warehouse was created
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}