// StockPro Inventory Management System
// Service: Report Service | Model: InventorySnapshot
// Developer: Suru | April 2026
// Description: Daily snapshot of stock quantity and value per product per warehouse

namespace ReportService.Models
{
    public class InventorySnapshot
    {
        // Unique ID auto-generated by database
        public int Id { get; set; }

        // Which warehouse this snapshot is for
        public int WarehouseId { get; set; }

        // Which product this snapshot is for
        public int ProductId { get; set; }

        // Quantity at time of snapshot
        public int Quantity { get; set; }

        // Stock value = Quantity x CostPrice
        public decimal StockValue { get; set; }

        // Date of snapshot
        public DateTime SnapshotDate { get; set; }

        // When record was created
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}