// StockPro Inventory Management System
// Service: Supplier Service | Model: Supplier
// Developer: Suru | April 2026
// Description: Represents a supplier in the supplier master register.
// Stores full contact details, payment terms, lead time, and performance rating.
// IsActive flag prevents new POs against inactive suppliers while preserving history.

namespace SupplierService.Models
{
    public class Supplier
    {
        // Unique supplier ID auto-generated by database
        public int Id { get; set; }

        // Supplier company name
        public string Name { get; set; } = "";

        // Primary contact person at supplier
        public string ContactPerson { get; set; } = "";

        // Contact email address
        public string Email { get; set; } = "";

        // Contact phone number
        public string Phone { get; set; } = "";

        // Full street address
        public string Address { get; set; } = "";

        // City where supplier is located — used for geo-filter queries
        public string City { get; set; } = "";

        // Country where supplier is located — used for geo-filter queries
        public string Country { get; set; } = "";

        // Tax identification number — must be unique per supplier
        public string TaxId { get; set; } = "";

        // Payment terms e.g. NET-30, NET-60, NET-90
        public string PaymentTerms { get; set; } = "NET-30";

        // Lead time in days — how long supplier takes to deliver
        public int LeadTimeDays { get; set; }

        // Performance rating 0.0 to 5.0 — updated after each goods receipt
        public decimal Rating { get; set; } = 0;

        // Is supplier active — inactive suppliers cannot receive new POs
        public bool IsActive { get; set; } = true;

        // When supplier was added to system
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        // When supplier record was last updated
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    }
}