// StockPro Inventory Management System
// Service: Movement Service | Model: StockMovement
// Developer: Suru | April 2026
// Description: Represents an immutable stock movement audit record.
// Movement types: STOCK_IN (GRN), STOCK_OUT (issue), TRANSFER_IN,
// TRANSFER_OUT, ADJUSTMENT, WRITE_OFF, RETURN.
// BalanceAfter enables historical stock-on-hand reconstruction.
// Movements are write-once — corrections made via opposing movement.

namespace MovementService.Models
{
    public class StockMovement
    {
        // Unique movement ID auto-generated by database
        public int Id { get; set; }

        // Which product this movement is for
        public int ProductId { get; set; }

        // Which warehouse this movement happened in
        public int WarehouseId { get; set; }

        // Movement type:
        // STOCK_IN = goods received from supplier (GRN)
        // STOCK_OUT = stock issued/consumed
        // TRANSFER_IN = stock received from another warehouse
        // TRANSFER_OUT = stock sent to another warehouse
        // ADJUSTMENT = manual correction
        // WRITE_OFF = damaged/expired/lost stock removal
        // RETURN = supplier or customer return
        public string MovementType { get; set; } = "";

        // Quantity moved — always positive
        public int Quantity { get; set; }

        // Reference ID — PO ID, issue order ID, transfer ID
        public string ReferenceId { get; set; } = "";

        // Reference type — PO, ISSUE, TRANSFER, AUDIT
        public string ReferenceType { get; set; } = "";

        // Unit cost at time of movement
        public decimal UnitCost { get; set; }

        // Who performed this movement
        public string PerformedBy { get; set; } = "";

        // Additional notes or reason
        public string Notes { get; set; } = "";

        // When movement happened
        public DateTime MovementDate { get; set; } = DateTime.UtcNow;

        // Stock balance after this movement — enables history reconstruction
        public int BalanceAfter { get; set; }
    }
}